### ISSUE TITLE
Background color not changing in onlyLabel mode

### ISSUE THREAD

**Issue by onurays** [Yalantis/Segmentio#39]
- Version of the component: 2.1
- Swift version: 3
- iOS version: 10.1
- Device: iPhone 7
- Xcode version: 8.1

You can reproduce this issue in your example project, by just changing the backgroundColor of default state from ```clear``` to ```white```. Background color of selected item is not changing.

![screen shot 2017-01-17 at 11 02 48](https://cloud.githubusercontent.com/assets/1254401/22012288/d85ab5fc-dc9b-11e6-8ec2-012089329758.png)
![screen shot 2017-01-17 at 11 03 07](https://cloud.githubusercontent.com/assets/1254401/22012287/d8568ac2-dc9b-11e6-9226-05e591d2a437.png)

**Comment by xergic** [comment]
I think this was fixed in the newest version, works fine for me (2.1.2 from Cocoapods).

**Comment by serejahh** [comment]
Hi @onurays. Please check the last version. Lemme know if it's not fixed

**Comment by onurays** [comment]
@xergic, @serejahh Unfortunately the problem still exists.

When view created, states are correct (white is selected):

![screen shot 2017-01-17 at 16 05 03](https://cloud.githubusercontent.com/assets/1254401/22021440/086c09a6-dcc6-11e6-9092-f2092707ccee.png)

Changing selection for the first time is also OK:

![image](https://cloud.githubusercontent.com/assets/1254401/22021454/262ccaf2-dcc6-11e6-96e0-3faa3342d070.png)

However, after changing the selection again, defaultBackground is gone:

![image](https://cloud.githubusercontent.com/assets/1254401/22021467/420d58e0-dcc6-11e6-863e-f8647986c8b7.png)

I will also try to debug your code as soon as possible.

**Comment by serejahh** [comment]
It would be great if you create a PR fixing the bug

**Comment by Tykhonkov** [comment]
Hello, @onurays looks like I have found the source of this bug. So soon I'll create PR to fix this issue.
